"""empty message

Revision ID: 079d439ecb0d
Revises: 23c6443aef58
Create Date: 2025-09-24 13:51:20.966075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '079d439ecb0d'
down_revision: Union[str, Sequence[str], None] = '23c6443aef58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_contribution_plan'), 'contribution_plan', type_='unique')
    op.create_unique_constraint(None, 'contribution_plan', ['portfolio_id'])
    op.drop_constraint(op.f('contribution_plan_target_id_fkey'), 'contribution_plan', type_='foreignkey')
    op.drop_column('contribution_plan', 'target_id')
    op.drop_column('riskprofile', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riskprofile', sa.Column('capacity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='risklevel'), autoincrement=False, nullable=False))
    op.add_column('contribution_plan', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('contribution_plan_target_id_fkey'), 'contribution_plan', 'target', ['target_id'], ['id'])
    op.drop_constraint(None, 'contribution_plan', type_='unique')
    op.create_unique_constraint(op.f('unique_contribution_plan'), 'contribution_plan', ['portfolio_id', 'target_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
