"""autogenerated revision

Revision ID: 23c6443aef58
Revises: 4707cbaa2167
Create Date: 2025-08-29 01:52:26.003283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c6443aef58'
down_revision: Union[str, Sequence[str], None] = '4707cbaa2167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variablecharacter', sa.Column('float', sa.Float(), nullable=True))
    op.add_column('variablecharacter', sa.Column('avgDailyTurnover', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variablecharacter', 'avgDailyTurnover')
    op.drop_column('variablecharacter', 'float')
    # ### end Alembic commands ###
