"""autogenerate revision

Revision ID: 26d13cc3edaa
Revises: f933050fd6dd
Create Date: 2025-08-27 06:52:48.086716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26d13cc3edaa'
down_revision: Union[str, Sequence[str], None] = 'f933050fd6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productcharacter')
    op.add_column('variablevalue', sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variablevalue', 'last_update')
    op.create_table('productcharacter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('std_dev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('beta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('benchmark', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sharpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('one_year_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('three_year_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('five_year_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ten_year_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('productcharacter_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('productcharacter_pkey'))
    )
    # ### end Alembic commands ###
