"""empty message

Revision ID: 2888792694cc
Revises: 73ccfe162e8c
Create Date: 2025-09-24 13:55:46.248085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2888792694cc'
down_revision: Union[str, Sequence[str], None] = '73ccfe162e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riskprofile', sa.Column('objective', sa.Enum('INDEPENDENCE', 'RETIREMENT', 'EDUCATION', 'OTHER', 'GROWTH', 'INCOME', name='wealthobjectivebase'), nullable=False))
    op.add_column('riskprofile', sa.Column('capacity', sa.Enum('LOW', 'MODERATE', 'HIGH', name='risklevel'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riskprofile', 'capacity')
    op.drop_column('riskprofile', 'objective')
    # ### end Alembic commands ###
