"""autogenerate revision

Revision ID: 33eeee405523
Revises: f4e303fe25ef
Create Date: 2025-08-16 11:26:27.777591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eeee405523'
down_revision: Union[str, Sequence[str], None] = 'f4e303fe25ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cashflowstatus', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashflowstatus', type_='foreignkey')
    # ### end Alembic commands ###
