"""autogenerate

Revision ID: 3854fe0b2f9d
Revises: 5a21ea64b99d
Create Date: 2025-08-19 12:21:50.182097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3854fe0b2f9d'
down_revision: Union[str, Sequence[str], None] = '5a21ea64b99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuer', sa.Column('img', sa.String(), nullable=True))
    op.add_column('product', sa.Column('product_class', sa.Enum('DEPOSIT', 'EQUITY', 'ETF', 'FUND', 'CRYPTO', 'MUTUAL_FUND', name='productclass'), nullable=True))
    op.drop_column('variable', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('type', postgresql.ENUM('STOCK', 'BOND', 'MUTUAL_FUND', 'MONEY_MARKET', 'ETF', 'COMMODITY', 'REAL_ESTATE', 'CRYPTOCURRENCY', 'OTHER', name='variabletype'), autoincrement=False, nullable=False))
    op.drop_column('product', 'product_class')
    op.drop_column('issuer', 'img')
    # ### end Alembic commands ###
