"""empty message

Revision ID: 3dc1aef4745b
Revises: e44ffb081aaa
Create Date: 2025-08-16 13:14:40.037953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc1aef4745b'
down_revision: Union[str, Sequence[str], None] = 'e44ffb081aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('type', sa.Enum('TARGET', 'GROWTH', 'EMERGENCY', 'LIQUID', 'INCOME', 'INVEST', name='portfoliotype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'type')
    # ### end Alembic commands ###
