"""autogenerated revision

Revision ID: 4707cbaa2167
Revises: 26d13cc3edaa
Create Date: 2025-08-29 01:49:37.946750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4707cbaa2167'
down_revision: Union[str, Sequence[str], None] = '26d13cc3edaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
