"""empty message

Revision ID: c997923de30f
Revises: 3dc1aef4745b
Create Date: 2025-08-16 13:16:41.014792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c997923de30f'
down_revision: Union[str, Sequence[str], None] = '3dc1aef4745b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'type',
               existing_type=postgresql.ENUM('TARGET', 'GROWTH', 'EMERGENCY', 'LIQUID', 'INCOME', 'INVEST', name='portfoliotype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'type',
               existing_type=postgresql.ENUM('TARGET', 'GROWTH', 'EMERGENCY', 'LIQUID', 'INCOME', 'INVEST', name='portfoliotype'),
               nullable=True)
    # ### end Alembic commands ###
