"""autogenerated revision

Revision ID: f933050fd6dd
Revises: 3854fe0b2f9d
Create Date: 2025-08-26 11:14:51.950937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f933050fd6dd'
down_revision: Union[str, Sequence[str], None] = '3854fe0b2f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('benchmark_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'variable', 'benchmark', ['benchmark_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.drop_column('variable', 'benchmark_id')
    # ### end Alembic commands ###
